  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXcUIs9yIldOUGEFJi1nfX9vMkaS8qiY',
    appId: '1:571665329297:web:4fc771c6de30d5735c2330',
    messagingSenderId: '571665329297',
    projectId: 'quranfyp-723e1',
    authDomain: 'quranfyp-723e1.firebaseapp.com',
    storageBucket: 'quranfyp-723e1.firebasestorage.app',
    measurementId: 'G-YZNH96F20Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWv3VgwEeETXKvlFkjOs9J1Vi8bApngI',
    appId: '1:571665329297:android:5d91e811fd03e2d35c2330',
    messagingSenderId: '571665329297',
    projectId: 'quranfyp-723e1',
    storageBucket: 'quranfyp-723e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgH-7tU9CxK_3gX9LmM-SWrvOc-XofcQ',
    appId: '1:571665329297:ios:c36bea6ac017b1555c2330',
    messagingSenderId: '571665329297',
    projectId: 'quranfyp-723e1',
    storageBucket: 'quranfyp-723e1.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlgH-7tU9CxK_3gX9LmM-SWrvOc-XofcQ',
    appId: '1:571665329297:ios:c36bea6ac017b1555c2330',
    messagingSenderId: '571665329297',
    projectId: 'quranfyp-723e1',
    storageBucket: 'quranfyp-723e1.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmXcUIs9yIldOUGEFJi1nfX9vMkaS8qiY',
    appId: '1:571665329297:web:4a53541967bbb4215c2330',
    messagingSenderId: '571665329297',
    projectId: 'quranfyp-723e1',
    authDomain: 'quranfyp-723e1.firebaseapp.com',
    storageBucket: 'quranfyp-723e1.firebasestorage.app',
    measurementId: 'G-2XJX09F95E',
  );

}